name: playze
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  google_fonts: ^4.0.4
  floating_bottom_navigation_bar: ^1.5.2
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.0.1
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

